### ISSUE TITLE
deleted_at is set on each auth/logout

### ISSUE THREAD

**Issue by trones** [rappasoft/vault#12]
Hi, 
I'm having trouble that the deleted_at and the remember_token is set on the user model each time i logout from the system so that when i try to login the authentication fails due to deleted_at is not null anymore. 

Anyone else bumped into this problem?

**Comment by rappasoft** [comment]
I can't replicate your issue. It uses the L5 default logout functionality and shouldn't modify it anywhere I can see. I've logged out a dozen times without issue just now. Is there any way I can try to replicate your issue?

**Comment by trones** [comment]
Basically i'm an idiot. The problem was that i somehow edited the table and ticked the On Update current_timestamp on the deleted_at column...
