### ISSUE TITLE
Error seeding

### ISSUE THREAD

**Issue by unixtime** [rappasoft/vault#13]
Getting the following error.

<pre>
php artisan db:seed --class="VaultTableSeeder"
</pre>

<pre>
[Illuminate\Database\QueryException]
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.deleted_at' in 'where clause' (SQL: select * from `users` where `users`.`deleted_at` is null limit 1)
</pre>

<pre>
[PDOException]
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.deleted_at' in 'where clause'
</pre>

Do I need to add <code>deleted_at</code> into the users table?

Thanks

**Comment by rappasoft** [comment]
Soft deletes on your user model are a prerequisite for the package.

**Comment by rappasoft** [comment]
http://laravel.com/docs/5.0/eloquent#soft-deleting

**Comment by unixtime** [comment]
got it. I was missing the column. Thank you.

**Comment by rappasoft** [comment]
No problem.
