### ISSUE TITLE
Wrong msg creating new users

### ISSUE THREAD

**Issue by isDOSe** [rappasoft/vault#16]
Hi,

When i try to create a new user without errors, the system goes back and put a danger message with "Invalid argument supplied for foreach()" but the user is created in db.

Sorry for my english xD
![error](https://cloud.githubusercontent.com/assets/6265846/6971403/17d4688c-d946-11e4-9ca6-200d74503257.jpg)

**Comment by NeDetto** [comment]
I have the same issue
whatch this https://github.com/rappasoft/vault/issues/14
If you found a solution please write here thanks :-)

**Comment by rappasoft** [comment]
I'll try to fix this today guys. 

Anthony Rappa

**Comment by isDOSe** [comment]
Thank you Anthony...

**Comment by isDOSe** [comment]
@NeDetto ... Do you have this issue too? #17

**Comment by rappasoft** [comment]
Pushed a fix, pull from composer or check the commit. Its just 1 function.
