### ISSUE TITLE
update "deleted at" on logout

### ISSUE THREAD

**Issue by isDOSe** [rappasoft/vault#17]
Vault update "deleted_at" field on logout action. This deletes my user and need to "null" the field again to log in.

**Comment by rappasoft** [comment]
This package doesn't have a logout method, it uses the default logout method that ships with L5. If you're having an issue with it, it is probably erroring from some other part in your project. Are you doing anything special anywhere when the user logs out?

**Comment by isDOSe** [comment]
No @rappasoft nothing special... Deleted_at field is updated when i edit any user... I want make you a question... In the installation section, do i need to add deleted_at field by myself?

**Comment by rappasoft** [comment]
Yes one of the per-requisites is to have deleted_at columns already. The 
reason for me not adding them in the migration is that if it was an 
existing project and the person already had then, the migration would fail.

**Comment by isDOSe** [comment]
oh i see... My project is completely new, with vault package only and cant edit users because the system updates "deleted_at" column eliminating my user...

If u want i will close this issue, i will create a new one project with new changes about "foreach problem" and let u know the results...

My mail is eflames at gmail, i added u to hangout.

Thanks for all Anthony

Kind regards.

**Comment by rappasoft** [comment]
I don't think you need to make a new project, but if you want to use my boilerplate, should be set up well to work with vault.
