### ISSUE TITLE
Overwrite validation

### ISSUE THREAD

**Issue by prodes** [rappasoft/vault#18]
Hi,

We're using your package and it is great. 
It saves us a lot of time, but we have one problem with it. 

We're using some different field. Instead of having a name field we're have multiple fields for firstname and lastname. 

Your validation file (vendor/rappasoft/vault/src/Vault/Services/Validators/Rules/Auth/User/Create.php) requires the name field which we don't have. 

I would like to know how we could overwrite this in our software. 

Best regards, 

Jurgen 

Keep up the good work!

**Comment by rappasoft** [comment]
Yes I will see if I can add a config option for it. 

Anthony Rappa

**Comment by prodes** [comment]
Perfect!

**Comment by rappasoft** [comment]
Ok you can do a composer update on your project. Please add this to the bottom of your vault.php config file and you should be able to change them and have them take effect. 

```
/*
     * Validation overwrites
     */
    'validation' => [
        'users' => [
            'create' => [
                'name'                  =>  'required',
                'email'                 =>  'required|email|unique:users',
                'password'              =>  'required|alpha_num|min:6|confirmed',
                'password_confirmation' =>  'required|alpha_num|min:6',
            ],
            'update' => [
                'email' =>  'required|email',
                'name'  =>  'required',
            ],
        ],
    ],
```
