### ISSUE TITLE
Update to docs

### ISSUE THREAD

**Issue by gregoryduckworth** [rappasoft/vault#2]
You need to update the docs to include adding:

`'Illuminate\Html\HtmlServiceProvider',` to the providers 
and 
`'Form'       => 'Illuminate\Html\FormFacade', 
'HTML'      => 'Illuminate\Html\HtmlFacade'` to the aliases

**Comment by rappasoft** [comment]
True, I don't know why I was under the impression adding them as dependencies would be enough. I think its because I use my boilerplate for testing and it already has them so it never errored. Would you like to make a pull request for this one?

**Comment by gregoryduckworth** [comment]
I've created #3 which updates them

**Comment by rappasoft** [comment]
Merged
