### ISSUE TITLE
Support for Laravel 5.1

### ISSUE THREAD

**Issue by UnderlineWords** [rappasoft/vault#25]
Hi,
Would it be possible to upgrade this package to work on Laravel 5.1? I guess your custom access package on  [laravel-5-boilerplate](https://github.com/rappasoft/laravel-5-boilerplate) is supported L5.1 now. Thank you!

**Comment by dennie170** [comment]
I just started making everything working on Laravel 5.1.  When I'm done, in a few days, I'll make a pull request, so sit tight!

**Comment by UnderlineWords** [comment]
Thanks for update and merge @dennie170 @rappasoft
