### ISSUE TITLE
Unable to deselect Administrator Role in Permission

### ISSUE THREAD

**Issue by shailesh91** [rappasoft/vault#5]
Hi, 
While trying out the package I noticed that while creating a new permission, I was unable to deselect the Administrator Role. 
Shailesh

**Comment by rappasoft** [comment]
Yes, my idea was the administrator should have all permissions. If you want to change it, publish the views and edit the view file to get rid of the readonly attribute.

**Comment by shailesh91** [comment]
Hmm. Thanks, I will do that!

**Comment by rappasoft** [comment]
Maybe i'll make it a config option in the next release.

**Comment by shailesh91** [comment]
That will be a good addition. Another thing, the package requires atleast one permission. Is that something on purpose?

**Comment by rappasoft** [comment]
It doesnt, if you don't see a delete box, edit the permission and uncheck 'system'. I just thought it would be a good idea to not accidentally delete some permissions if used everywhere.

**Comment by shailesh91** [comment]
Hmm. Thanks for the assist.
