### ISSUE TITLE
radic/blade-extensions and laravel 5

### ISSUE THREAD

**Issue by makstr** [rappasoft/vault#6]
Hello Anthony, 

I am building an app on top of you laravel 5 boilerplate and vault. I noticed you have a mention of blade extensions which I would very much like to use. Unfortunately I have trouble installing the suggested radic/blade-extensions. Below are my composer update conflicts. How did you get that to work?

Thanks,
Peter

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.0.2
    - Installation request for radic/blade-extensions 1.2 -> satisfiable by radic/blade-extensions[v1.2.0].
    - Conclusion: don't install laravel/framework v5.0.2
    - Conclusion: don't install laravel/framework v5.0.1
    - radic/blade-extensions v1.2.0 requires illuminate/support 4.\* -> satisfiable by illuminate/support[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.1, v4.2.12, v4.2.16, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/support v4.0.0|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.1|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.10|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.2|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.3|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.4|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.5|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.6|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.7|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.8|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.9|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.0|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.1|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.10|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.11|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.12|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.13|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.14|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.15|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.16|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.17|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.18|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.19|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.2|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.20|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.21|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.22|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.23|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.24|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.25|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.26|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.27|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.28|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.29|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.3|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.30|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.4|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.5|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.6|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.7|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.8|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.9|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.1|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.12|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.16|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.2|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.3|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.4|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.5|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.6|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.7|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.8|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.9|don't install laravel/framework v5.0.0
    - Installation request for laravel/framework 5.0.\* -> satisfiable by laravel/framework[v5.0.0, v5.0.1, v5.0.2].

**Comment by rappasoft** [comment]
Hmm you're right it seems to be locked into L4 for now so I'll take out the suggest. But vault comes with two of its own as of yesterday.

**Comment by makstr** [comment]
I just realized vault does all that by itself :)

**Comment by rappasoft** [comment]
Ah yes it's new! I like it. I'm going to remove the suggest off the boilerplate and close this, and work on your other issue.
